config/routes.rb
Rails.application.routes.draw do
  resources :pics
  devise_for :users
  resources :users, :only => [:show]

  root "pages#home"
  get "about" => "pages#about"
  get 'tags/:tag', to: 'pics#index', as: :tag
  get 'users/:id' => 'users#show', as: :profile

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :big => "900x900>", :large => "600x600>", :medium => "400x400>", :thumb => "100x100>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	validates :image, presence: true
	
	acts_as_taggable
	acts_as_taggable_on :tag_list
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pics, dependent: :destroy
  validates :name, presence: true

  def to_param
  	"#{id} #{name}". parameterize
  end	
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	redirect_to profile_path(current_user.id) if user_signed_in?
  end

  def about
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /pics
  def index
    if params[:tag]
      @pics = Pic.tagged_with(params[:tag])
    else
      @pics = current_user.pics.order "created_at DESC"
    end
  end

  # GET /pics/1
  def show
  end

  # GET /pics/new
  def new
    @pic = current_user.pics.build
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics
  def create
    @pic = current_user.pics.build(pic_params)

    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render :show, status: :created, location: @pic }
      else
        format.html { render :new }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url, notice: 'Pic was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    def correct_user
      @pic = current_user.pics.find_by(id: params[:id])
      redirect_to pics_path, notice: "You can't edit this pic" if @pic.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:tag_list, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

	def show
  	@user = User.find(params[:id])
  	@pics = current_user.pics
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "#my.Pics", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pic_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pic
            <% end %>
          </li>

          <li><%= link_to "My Account", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li> 
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mypics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do | name, msg | %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<%= yield %>
	</div>

	 <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron">
	<h1>#my.Pics</h1>
	<p> tagmy.Pics helps you to organize your photos easy and beautifully!</p>
	<p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
	<br/>
	Already have an account? <%= link_to "Log In", new_user_session_path %>
</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>About MyPics</h1>
	<p> MyPics is goint to help you Organize your photos easy and beatifuly!</p>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>#my.Pics</h1>
	<p> tagmy.Pics helps you to organize your photos easy and beautifully!</p>
	<p><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
	<br/>
	Already have an account? <%= link_to "Log In", new_user_session_path %>
</div>

app/views/pics/_form.html.erb
<%= form_for @pic, html: { multipart: true }  do |f| %>
	<% if @pic.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

			<ul>
			<% @pic.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		</div>
	<% end %>


		<div class="form-group">
			<%= f.label :image %>
			<%= f.file_field :image %> <br />
		</div>

		<div class="form-group">
			<%= f.label :tag_list, "Tags (separated by commas)" %>
			<%= f.text_field :tag_list, class: "form-control" %> <br />
		</div>

		<div class="actions">
			<%= f.submit class: "btn btn-primary" %>
		</div>


<% end %>

app/views/pics/edit.html.erb
<p><%= link_to '<< Back', pics_path %></p>

<div class="panel panel-default">
  <div class="panel-heading">
		<h1>Editing pic</h1>
	</div>

	 <div class="panel-body">
	 	 <div class="row">
      <div class="col-md-6">
      	<div class="form-group">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>

	 <div class="panel-footer">
		<%= link_to 'Show', @pic %>
	</div>

</div>

app/views/pics/index.html.erb
<div id="tag_cloud">
	<div class="panel panel-default" style="text-align: center">
			<div class="panel-body">
				<% tag_cloud Pic.tag_counts, %w[s m l] do |tag, css_class| %>
					<%= link_to "##{tag.name}", tag_path(tag.name), class: css_class %>
				<% end %>
			</div>
	</div>
</div>

<div id="pic" class="transitions-enabled">
	<% @pics.each do |pic| %>
		
		<div class="box panel panel-default">
			<%= link_to image_tag(pic.image.url(:medium)), pic %>
			
			<div class="panel-body">
				<%= pic.tag_list.map { |p| link_to "##{p}", tag_path(p) }.join(" ").html_safe %>		
					
					<% if current_user && pic.user == current_user %>
					
						<div class="actions">
							<%= link_to edit_pic_path(pic) do %>
								<span class= "glyphicon glyphicon-edit"></span>
							<% end %>
							
							<%= link_to pic, method: :delete, data: { confirm: 'Are you sure?' } do %>
								<span class="glyphicon glyphicon-trash"></span>
							<% end %>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/pics/my-pics.erb
<div id="pic" class="transitions-enabled">
	<% @pics.each do |pic| %>
		<div class="box panel panel-default">
			<%= link_to image_tag(pic.image.url(:medium)), pic %>
			<div class="panel-body">
				<%= pic.tag %>		
				<% if current_user && pic.user == current_user %>
					
					<div class="actions">
						<%= link_to edit_pic_path(pic) do %>
							<span class= "glyphicon glyphicon-edit"></span>
							Edit
						<% end %>
            
            <%= link_to pic, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>

					</div>
				<% end %>
			</div>
		</div>
	<% end %>

</div>

app/views/pics/my-pics.html.erb
<div id="pic" class="transitions-enabled">
	<% @pics.each do |pic| %>
		<div class="box panel panel-default">
			<%= link_to image_tag(pic.image.url(:medium)), pic %>
			<div class="panel-body">
				<%= pic.tag %>		
				<% if current_user && pic.user == current_user %>
					
					<div class="actions">
						<%= link_to edit_pic_path(pic) do %>
							<span class= "glyphicon glyphicon-edit"></span>
							Edit
						<% end %>
            
            <%= link_to pic, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>

					</div>
				<% end %>
			</div>
		</div>
	<% end %>

</div>

app/views/pics/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
		<h1>New pic</h1>
	</div>

	  <div class="panel-body">
	  	<div class="row">
      	<div class="col-md-6">
			<%= render 'form' %>
				</div>
			</div>
		</div>

  	<div class="panel-footer text-black">
			<%= link_to 'Back', pics_path %>
		</div>

</div>

app/views/pics/show.html.erb
<body id="pic-show">
	<p><%= link_to '<< Back', pics_path %></p>

		<div class="panel panel-black">
		  <div class="panel-heading-dark" style="text-align: center">
				<%= image_tag @pic.image.url(:big)  %>
			</div>

			<div class="panel-body panel-body-black">
				<p><%= @pic.tag_list.map { |p| link_to "##{p}", tag_path(p) }.join(" ").html_safe  %></p>

					<% if current_user && @pic.user == current_user %>
						<%= link_to edit_pic_path(@pic) do %>
							<span class= "glyphicon glyphicon-edit"></span>
							Edit
						<% end %>

			</div>

		</div>
	<% end %>
</body>

app/views/users/show.html.erb
<div id="tag_cloud">
	<div class="panel panel-default" style="text-align: center">
			<div class="panel-body">
				<% tag_cloud Pic.tag_counts, %w[s m l] do |tag, css_class| %>
					<%= link_to "##{tag.name}", tag_path(tag.name), class: css_class %>
				<% end %>
			</div>
	</div>
</div>

<div id="pic" class="transitions-enabled">
	<% @pics.each do |pic| %>
		
		<div class="box panel panel-default">
			<%= link_to image_tag(pic.image.url(:medium)), pic %>
			
			<div class="panel-body">
				<%= pic.tag_list.map { |p| link_to "##{p}", tag_path(p) }.join(" ").html_safe %>		
					
					<% if current_user && pic.user == current_user %>
					
						<div class="actions">
							<%= link_to edit_pic_path(pic) do %>
								<span class= "glyphicon glyphicon-edit"></span>
							<% end %>
							
							<%= link_to pic, method: :delete, data: { confirm: 'Are you sure?' } do %>
								<span class="glyphicon glyphicon-trash"></span>
							<% end %>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
</div>